### ISSUE TITLE
adding a --no-sessions option

### ISSUE THREAD

**Issue by sarahoh** [jmtyszka/CBICQC#1]
Hello,
This is a minor feature request to avoid having to manually add a level of hierarchy for scan session to our data folders.
If possible, would you be able to add a --no-sessions option to cbicqc, similar to the bidskit option?

Thank you! :)

**Comment by jmtyszka** [comment]
Thanks @sarahoh. The latest release (2022.2.28.1) now includes a --no-sessions option. Use this if you have no session folders in your BIDS dataset. Let me know if you run into any problems using this flag.
